# 01.30 

## Python : 예외 처리



### 

:mortar_board: **try & except**

```python
try:
    num = input()
    print(int(num))
except ValueError:
    print('숫자를 입력하시오 :')
    
---------------------
do
숫자를 입력하시오 :

```

 오류가 나지 않으면 try문이 특정 오류가 나면 except문이 실행된다.  except문을 여러개 사용할 수 있지만 작은 범위의 오류부터 작성해야한다. (Exception이 가장 크므로 제일 뒤에 작성)



:mortar_board: **else**

 에러가 없는 경우 else문을 실행한다. except문이 실행되지 않아야 else문이 실행된다. 



:mortar_board: **finally**

 예외 발생 여부와 상관없이 반드시 수행되어야 한다.



:mortar_board: **as**

 에러 메시지 처리 `as`를 활용하여 에러메시지를 보여 줄 수 있다.  

```python
try:
    <코드 1>
except 예외 as err:
    <코드 2>

```

err은 에러 설명 구문이다. 



:mortar_board:  **예외 발생 raise / assert** 

 `raise` 문을 통해 예외를 발생시킬 수 있고, `assert`는 `Boolean expression`구문이 거짓 일 경우 error message가 발생한다. 

```python
raise ValueError('안녕')

--------------------------
ValueError : 안녕
```

```python
assert len([1]) == 2, '길이가 맞지 않습니다.'

--------------------------
AssertionError : 길이가 맞지 않습니다. 
```



